### ISSUE TITLE
make install error - mintkey

### ISSUE THREAD

**Issue by debragail** [BitSongOfficial/go-bitsong#10]
<img width="1073" alt="Screen Shot 2019-06-03 at 14 23 17" src="https://user-images.githubusercontent.com/552529/58835727-8ffd1180-860b-11e9-8c4b-8678cf7be025.png">
<img width="717" alt="Screen Shot 2019-06-03 at 14 12 35" src="https://user-images.githubusercontent.com/552529/58835728-8ffd1180-860b-11e9-92ef-9cd4ebe40f2e.png">

**Comment by debragail** [comment]
https://github.com/cosmos/cosmos-sdk/pull/4475

**Comment by debragail** [comment]
10.10.5 Yosemite

Why would i run make make install?

**Comment by angelorc** [comment]
Did you followed the instructions reported here?
[https://github.com/BitSongOfficial/go-bitsong/blob/develop/README.md](https://github.com/BitSongOfficial/go-bitsong/blob/develop/README.md)

**Comment by debragail** [comment]
yes
