### ISSUE TITLE
Sinfonia Testnet bug report

### ISSUE THREAD

**Issue by Uladzik14** [bitsongofficial/go-bitsong#102]
I can't do swap when the step size is too big (170.444444444444 etc).
it doesn't even pop up a "transaction failed" message
my bitsong wallet bitsong1w60q3k507d9phcs7qqezt88w3ux5pzrlajhyd2

![image](https://user-images.githubusercontent.com/105236630/167465870-3c81ae3f-00b4-403a-8748-05c69f3294cf.png)

**Comment by Uladzik14** [comment]
> I can't do swap when the step size is too big (170.444444444444 etc). it doesn't even pop up a "transaction failed" message
> 
> ![image](https://user-images.githubusercontent.com/105236630/167465870-3c81ae3f-00b4-403a-8748-05c69f3294cf.png)

my bitsong wallet bitsong1w60q3k507d9phcs7qqezt88w3ux5pzrlajhyd2

**Comment by Giorgionocera** [comment]
This is not the right repository to add issues for Sinfonia. 
Please give a look at the correct repo, there are different issues with the same "problem". 
So please, avoid duplicated issues.
