### ISSUE TITLE
Sinfonia Tesnet Bug report

### ISSUE THREAD

**Issue by Bams25th** [bitsongofficial/go-bitsong#107]
I want to see the transactions that I have made, on the testnet web image below there are several failed transactions and only marked with the words "broadcasting" . then I pressed the view all button and entered the mintscan.io web from osmosis, but I looked down in the transaction section there was no transaction record at all and it was shown in the image 2 below. then i checked in the keplr wallet there was a token transaction on osmosis testnet it was shown in the image 3 below.

fix this bug, all transactions should be recorded clearly and if it fails the failure should be clearly written on webscan or mintscan.io/osmosis and also written "failed" in the transaction history in the swap menu. and please if the transaction fails, put a mark in the transaction section as "failed" not "broadcasting", if it is written broadcasting it means the transaction is still running but not failed.

I'm confused why there are no transactions written on the mintscan.io web/osmosis, even though the button "view all"  goes directly to that web ??

is there any typo coding for the click of a button that goes straight to the web?
or indeed the transaction is not written on mintscan.io/osmosis? but it written on another web scan?
please check it again ...

this my wallet bitsong testnet :
bitsong1e7tpgjy8kfvfsm4f7uypjvsw9hfdqsustpwvm8

this my wallet osmosis :
osmo1pe9gx7yzuzuw8qw60hnhscz2n9p6m2nlwdqu72

![2022-05-10 (1)](https://user-images.githubusercontent.com/91352531/167467529-8f54e6e8-9cfd-4579-b8f5-dfde49a908b9.png)
![2022-05-10 (2)](https://user-images.githubusercontent.com/91352531/167467537-654c9a01-65f2-4e5e-a7ce-0b1aaf305be9.png)
![2022-05-10 (3)](https://user-images.githubusercontent.com/91352531/167468414-7c1409f9-23ac-46a6-88ab-27cfbed16c47.png)

**Comment by Giorgionocera** [comment]
This is not the right repository to add issues for Sinfonia. 
Please give a look at the correct repo, there are different issues with the same "problem". 
So please, avoid duplicated issues.
