### ISSUE TITLE
Can't swap and solution

### ISSUE THREAD

**Issue by Dikad1866** [bitsongofficial/go-bitsong#109]
![Screenshot_2022-05-10-01-31-34-776_com yandex browser alpha](https://user-images.githubusercontent.com/97156271/167477622-33bbd358-e6b7-4cd7-946b-0cf4f00f2127.jpg)

when I first tried the swap feature, there was a slight bug, namely the swap failed, and to solve that problem every time I wanted to swap or make a transaction I refreshed the web page,,, and everything was normal and smooth, thank you
this is my address
bitsong1wqm3h0sc9zujeq4zn7ewhsvy6tgj3mcsgud5yv

**Comment by Giorgionocera** [comment]
This is not the right repository to add issues for Sinfonia. 
Please give a look at the correct repo, there are different issues with the same "problem". 
So please, avoid duplicated issues.
