### ISSUE TITLE
make install error - cosmos-sdk

### ISSUE THREAD

**Issue by debragail** [BitSongOfficial/go-bitsong#11]
<img width="1068" alt="Screen Shot 2019-06-03 at 16 54 34" src="https://user-images.githubusercontent.com/552529/58842082-6e0e8980-8621-11e9-8147-0d6d65c93642.png">

**Comment by debragail** [comment]
<img width="1068" alt="Screen Shot 2019-06-03 at 17 04 07" src="https://user-images.githubusercontent.com/552529/58842122-a1e9af00-8621-11e9-8f91-f63e32c81d00.png">

**Comment by angelorc** [comment]
Hello,
can I ask which "Operating System" you use?

Can you try `make` before `make install`

**Comment by debragail** [comment]
i'm on Mac OS why would i do make make install?

**Comment by debragail** [comment]
@angelorc why was this closed?
