### ISSUE TITLE
Bug in estimated slippage and slippage tolerance

### ISSUE THREAD

**Issue by Adjip25** [bitsongofficial/go-bitsong#110]
![AE5CD4D2-73B7-45C4-A176-5E3195600255](https://user-images.githubusercontent.com/101589290/167479605-6c826a07-eda6-4587-b919-731d6cb63851.jpeg)
![40263E03-C7B3-4047-AD07-CA607A35596E](https://user-images.githubusercontent.com/101589290/167479619-01880f97-ae1f-4006-918d-2c1d390f8d71.jpeg)

I think i found a bug and perhaps it can make a confused for the user. As seen in the picture, in estimated slippage there is no big impact after i changed slippage tolerance from 1% to 5%. Thank you

My address: bitsong1nqyn8g22e8wpjjhll33j2tj36yn7n08yd9e6cz

**Comment by Giorgionocera** [comment]
This is not the right repository to add issues for Sinfonia. 
Please give a look at the correct repo, there are different issues with the same "problem". 
So please, avoid duplicated issues.
