### ISSUE TITLE
Bug Sinfonia Testnet

### ISSUE THREAD

**Issue by patasana** [bitsongofficial/go-bitsong#113]
I can not add liquidity D9/BTSG pool for the fist time. The second time it is ok. 
My wallet : bitsong187z3p9p8dqt6w2y0cs9k53yrus4gjs3jll2pes 
![000](https://user-images.githubusercontent.com/101321289/167499992-554e251a-b04c-4d7e-bb28-16aca731289b.png)

**Comment by Giorgionocera** [comment]
This is not the right repository to add issues for Sinfonia. 
Please give a look at the correct repo, there are different issues with the same "problem". 
So please, avoid duplicated issues.
