### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by yclaxt** [bitsongofficial/go-bitsong#114]
In transfering screen, if available asset is zero; amount looks -0.025

My adress: bitsong1djytet30fzdf8cq0tm7wx8m8kw8qfzuw7my2hs
![image](https://user-images.githubusercontent.com/99393823/167512183-19916a73-9d71-4915-af01-2f8a65ce628d.png)

**Comment by vieadzawiyah** [comment]
Many other members of group told that if we start swapping must transfer tBTSG to osmosis tesnet and when i want to transfer it. Sometimes  I cant transfer my tBTSG (Bitsong Tesnet) to Osmosis Tesnet. Sometimes amount of token was disappeared.
bitsong162gfjny5grcf5f2e6p8rq9gsxa9ykxkc72rq3n
(My address) Wishing you can accept my report bug thank you in advance

https://user-images.githubusercontent.com/105254172/167520913-263c834e-41a2-433b-95a7-8f2f89aef5a4.mp4


https://user-images.githubusercontent.com/105254172/167520951-ca38ac75-a8d1-4268-8e6e-c7552d8b175f.mp4

**Comment by Giorgionocera** [comment]
This is not the right repository to add issues for Sinfonia. 
Please give a look at the correct repo, there are different issues with the same "problem". 
So please, avoid duplicated issues.
