### ISSUE TITLE
My sugestion

### ISSUE THREAD

**Issue by Shintawati03** [bitsongofficial/go-bitsong#115]
I think the selection of icons such as swap, add liquidity and transfer should be in the main menu to make it look easier and simpler... and my suggestion is that the color selection in the bounds is very faint and almost invisible, it would be better if you did that color change
![Screenshot_20220510-055655_Kiwi Browser](https://user-images.githubusercontent.com/105250804/167513115-56d2052a-09d1-4043-803f-2e809a69cc72.jpg)
![Screenshot_20220510-055648_Kiwi Browser](https://user-images.githubusercontent.com/105250804/167513119-37bf892f-b00c-4ed0-9157-f1f27a711abf.jpg)
![Screenshot_20220510-054700_Kiwi Browser](https://user-images.githubusercontent.com/105250804/167513121-73a5f679-4230-473d-aabf-d01d1d884440.jpg)

**Comment by vieadzawiyah** [comment]
My suggestion is we don't need to transfer btsg from bitsong tesnet to osmosis tesnet so it is more simple and easier  but for every transaction was very fast n smooth i very like 

bitsong162gfjny5grcf5f2e6p8rq9gsxa9ykxkc72rq3n
(My address)

**Comment by vieadzawiyah** [comment]
![IMG-20220510-WA0007](https://user-images.githubusercontent.com/105254172/167521860-0a4fa349-ec02-49ce-8777-f1ef90528718.jpg)

My suggestion is we don't need to transfer btsg from bitsong tesnet to osmosis tesnet so it is more simple and easier  but for every transaction was very fast n smooth i very like 

bitsong162gfjny5grcf5f2e6p8rq9gsxa9ykxkc72rq3n
(My address)

**Comment by vieadzawiyah** [comment]
![IMG_20220510_080339](https://user-images.githubusercontent.com/105254172/167522325-268b1633-ba2c-45c7-8023-66bf2497e03d.jpg)

My suggestion is we don't need to transfer btsg from bitsong tesnet to osmosis tesnet so it is more simple and easier  but for every transaction was very fast n smooth i very like 

bitsong162gfjny5grcf5f2e6p8rq9gsxa9ykxkc72rq3n
(My address)

**Comment by Giorgionocera** [comment]
This is not the right repository to add issues for Sinfonia. 
Please give a look at the correct repo, there are different issues with the same "problem". 
So please, avoid duplicated issues.
