### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Oleps02** [bitsongofficial/go-bitsong#119]
I had this error. bitsong19uts2g8t72nzm7antmht0mtjyt7ylym4wmt8ap
![My error](https://user-images.githubusercontent.com/102989932/167622091-a87fbef8-920a-413d-9be2-2a513cb364ed.png)

**Comment by Giorgionocera** [comment]
This is not the right repository to add issues for Sinfonia. 
Please give a look at the correct repo, there are different issues with the same "problem". 
So please, avoid duplicated issues.
