### ISSUE TITLE
tendermint error

### ISSUE THREAD

**Issue by debragail** [BitSongOfficial/go-bitsong#12]
![Screen Shot 2019-06-08 at 12 35 53 AM](https://user-images.githubusercontent.com/552529/59144121-ba422c80-8987-11e9-97f7-a1da591bde50.png)

**Comment by angelorc** [comment]
Before `bitsongd start`, you need to generate the genesis file (as described here [https://github.com/BitSongOfficial/go-bitsong#running-the-test-network-and-using-the-commands](https://github.com/BitSongOfficial/go-bitsong#running-the-test-network-and-using-the-commands)

Example:

```
bitsongd init --chain-id bitsong-test-network-1

# Copy the `Address` output here and save it for later use
# [optional] add "--ledger" at the end to use a Ledger Nano S
bitsongcli keys add jack

# Copy the `Address` output here and save it for later use
bitsongcli keys add alice

# Add both accounts, with coins to the genesis file
bitsongd add-genesis-account $(bitsongcli keys show jack -a) 1000btsg
bitsongd add-genesis-account $(bitsongcli keys show alice -a) 1000btsg

# Configure your CLI to eliminate need for chain-id flag
bitsongcli config chain-id bitsong-test-network-1
bitsongcli config output json
bitsongcli config indent true
bitsongcli config trust-node true
```

**Comment by debragail** [comment]
I did those steps and still get the error because the genisis.json returns nil.  Why do you keep closing this issue?
