### ISSUE TITLE
Balance not updated for Swap

### ISSUE THREAD

**Issue by Mrfreshz** [bitsongofficial/go-bitsong#121]
My bitsong balance is showing 0 BTSG under Swap but shows 10,000 BTSG under Assets. I think this is a bug that need to be fix. 

Wallet address: bitsong15nf8v5aj7t86avkcdtz9djlydevmzcsdr0wpyq 

![{6A1A7E63-8889-4D72-A123-710E4770791D} png](https://user-images.githubusercontent.com/57938278/167706432-40a8b444-0c39-45bd-af0b-ec9005b386ca.jpg)
![{6EDEA9A4-6BB1-4FEB-82B2-F7942D746BA7} png](https://user-images.githubusercontent.com/57938278/167706468-95b7cbe5-f4ed-4253-8f57-cf05205a7afb.jpg)

**Comment by Giorgionocera** [comment]
This is not the right repository to add issues for Sinfonia. 
Please give a look at the correct repo, there are different issues with the same "problem". 
So please, avoid duplicated issues.
