### ISSUE TITLE
Bitsong Testnet

### ISSUE THREAD

**Issue by ayennn** [bitsongofficial/go-bitsong#122]
![Screenshot (251)](https://user-images.githubusercontent.com/56185383/167735848-23c76155-ed81-4c88-9ed9-7b410f45687a.png)

bitsong160z0dte5mtaxcug8jwgkw3wx39qv0xj0ey5mh9

**Comment by Giorgionocera** [comment]
This is not the right repository to add issues for Sinfonia. 
Please give a look at the correct repo, there are different issues with the same "problem". 
So please, avoid duplicated issues.
