### ISSUE TITLE
BUG add liquidity in pools #9: CLAY/BTSG

### ISSUE THREAD

**Issue by fathurrs20** [bitsongofficial/go-bitsong#128]
Error Message
![image](https://user-images.githubusercontent.com/76474290/168441164-c9ac5584-7908-4614-a2a3-9061483bf719.png)

my wallet
![image](https://user-images.githubusercontent.com/76474290/168441256-ad3a7f54-879c-424b-8fff-afa770eff9c1.png)

I found this bug when I wanted to add liquidity in pools #9: CLAY/BTSG
my bitsong address : bitsong1fkryrxusmhdjv9js7jvkw3gsfwafna0vnrsahl

**Comment by Giorgionocera** [comment]
This is not the right repository to add issues for Sinfonia. 
Please give a look at the correct repo, there are different issues with the same "problem". 
So please, avoid duplicated issues.
