### ISSUE TITLE
init error

### ISSUE THREAD

**Issue by debragail** [BitSongOfficial/go-bitsong#13]
![Screen Shot 2019-06-08 at 1 01 33 AM](https://user-images.githubusercontent.com/552529/59144232-82d47f80-8989-11e9-97c1-b3f53c02e065.png)

**Comment by debragail** [comment]
missing an argument in the README steps.

Tried bitsongd init genesis but got an error when trying to start

![Screen Shot 2019-06-08 at 1 04 34 AM](https://user-images.githubusercontent.com/552529/59144238-a0a1e480-8989-11e9-90c4-614885c8640c.png)

**Comment by debragail** [comment]
i cleared everything and retried and still an error

**Comment by angelorc** [comment]
try with 

```
bitsongd init MyMoniker --chain-id bitsong-test-network-1
```

Please, do not use screenshot here, but you can use text

**Comment by debragail** [comment]
you need to update the README instructions.  Why can't I use screenshots?

**Comment by debragail** [comment]
I get the same error

**Comment by debragail** [comment]
I get the same error.  I can't work on the bounty if you're going to close my issues.
