### ISSUE TITLE
Bug found.. huge token reduction

### ISSUE THREAD

**Issue by AyoAden** [bitsongofficial/go-bitsong#131]
The value of the bitsong token reduces leading to a reduction in the value and quantity of the token in the testnet version after adding to pool and converting back to the native token.. if the goal of each tester is get more than 10k token then with the reduction it's going to  impossible to get more than 10k token..I started my test with 10k token, when removing and converting back I got 7k back I think this is a huge reduction which shouldn't have occurred. Pls look into this

**Comment by ctrl-Felix** [comment]
This is not a bug but a common market mechanism. With the testneto coming to its end and everyone has to liquidate the fantokens back to BTSG this had to happen. Many have more than 10k which means it is/was possible. 
That's how a competition works
