### ISSUE TITLE
Change the error message for invalid symbol

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/go-bitsong#140]
In the error message for invalid symbol https://github.com/bitsongofficial/go-bitsong/blob/b395f13fbacbf68ca925a8917b344b8955aa5dfe/x/fantoken/types/validation.go#L57
I would change the string

from
`invalid symbol: %s, only accepts english lowercase letters and numbers, length [%d, %d], and begin with an english letter, regexp: %s`

to
`invalid symbol: %s, only accepts English lowercase letters and numbers, length [%d, %d], regexp: %s`

**Comment by angelorc** [comment]
solved in commit 8fbedc9a37f3008d7ecbd710c237c6832e4bdf9c
