### ISSUE TITLE
marshaling error: json: unsupported type: func() uint64

### ISSUE THREAD

**Issue by wwwAndries** [bitsongofficial/go-bitsong#149]
AMD Ryzen 9 5950X
128 GB RAM
Ubuntu 22.04 LTS
Bitsongd 0.11.0

I came accross these marshaling errors in the bitsongd log:

7:53PM INF acknowledgement written dst_channel=channel-0 dst_port=transfer module=x/ibc/channel sequence="marshaling error: json: unsupported type: func() uint64" src_channel=channel-73 src_port=transfer

**Comment by angelorc** [comment]
this bug have been discussed in our discord channel, it seem to be related to the relayer and ibc
