### ISSUE TITLE
Proposal Handler for NFT fees

### ISSUE THREAD

**Issue by giorgionocera** [bitsongofficial/go-bitsong#155]
In the `nft` module, it could be useful to add a new proposal handler to manage a custom proposal that could be used to change the NFTs issuing fees. An example of such a thing could be found in the `fantoken` module from line 54:
https://github.com/bitsongofficial/go-bitsong/blob/84691c819214a1f9b9dd844ea2b49b7ccc8ece1b/x/fantoken/handler.go#L54-L80

**Comment by angelorc** [comment]
Yes, this is very useful

**Comment by go-btsg** [comment]
Since nft issue fee is in params, it's not needed to add custom proposal, this can be done with ParamsUpdateProposal with `nft` subspace in it.

**Comment by angelorc** [comment]
`the specific proposal handler is just a nice to have :) and could be implemented in an hour`

we discussed it in our telegram group
