### ISSUE TITLE
Genesis Type definition

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/go-bitsong#156]
In the `nft` module, the Genesis Type definition lays on the `nft/genesis.go` file
https://github.com/bitsongofficial/go-bitsong/blob/84691c819214a1f9b9dd844ea2b49b7ccc8ece1b/x/nft/genesis.go#L9-L18 

In the `fantoken` module, it lays on the `fantoken/types/genesis.go` instead.
https://github.com/bitsongofficial/go-bitsong/blob/84691c819214a1f9b9dd844ea2b49b7ccc8ece1b/x/fantoken/types/genesis.go#L4-L9

For a matter of codebase coherence, it could be better to make uniform the implementation and choose where to put this definition, even for future modules.
IMHO, it could lay on the `module/types/genesis.go` file, but, let me know if there is any advice on moving it to the `genesis.go` file.

**Comment by go-btsg** [comment]
I think it's not a problem - but if it's needed to have same coding style as fantoken module, it can be moved.

**Comment by Giorgionocera** [comment]
It is done in commit [b3d719a](https://github.com/bitsongofficial/go-bitsong/commit/b3d719ad03c305c9289e775f45c033cdb6dabcec)
