### ISSUE TITLE
Suggestion for proto structure

### ISSUE THREAD

**Issue by giorgionocera** [bitsongofficial/go-bitsong#158]
It could be useful to separate the proto definitions in the `nft` module. At the moment, both the `nft` (and the side) definitions, the definition of the `Params`

https://github.com/bitsongofficial/go-bitsong/blob/84691c819214a1f9b9dd844ea2b49b7ccc8ece1b/proto/bitsong/nft/v1beta1/nft.proto#L74-L82

and the definition of the `Events`

https://github.com/bitsongofficial/go-bitsong/blob/84691c819214a1f9b9dd844ea2b49b7ccc8ece1b/proto/bitsong/nft/v1beta1/nft.proto#L84-L145

lay on the [`nft.proto`](https://github.com/bitsongofficial/go-bitsong/blob/candymachine_updates/proto/bitsong/nft/v1beta1/nft.proto) file.

It could be useful to separate the definitions in different files (i.e., `events.proto` and `params.proto`), as it is done on the `fantoken` module.
What do you think about that?

**Comment by go-btsg** [comment]
It can be done like that.
