### ISSUE TITLE
Marketplace royalties not verified creator

### ISSUE THREAD

**Issue by giorgionocera** [bitsongofficial/go-bitsong#160]
In the `marketplace` module, there is a method that processes the shares of the royalties for "not-primary" sales.
The `ProcessRoyalties` method

https://github.com/bitsongofficial/go-bitsong/blob/84691c819214a1f9b9dd844ea2b49b7ccc8ece1b/x/marketplace/keeper/royalties.go#L8-L37

Send coins to the creators, but it does not check if the creators are already verified.
I think that if a creator is not verified for an NFT, he should not receive the royalties. IMHO those coins should be sent to the community pool.

What do you think?

**Comment by go-btsg** [comment]
Hmm, provide it to rest of the members or if noone verified it, just send full to community pool?

**Comment by angelorc** [comment]
What happen if the creator is not verified? Should we send the funds to the community pool?

**Comment by Giorgionocera** [comment]
We could also think to avoid their usage from the marketplace.
