### ISSUE TITLE
NFT seq value

### ISSUE THREAD

**Issue by giorgionocera** [bitsongofficial/go-bitsong#161]
In the `nft` module, the `NFT` object is defined as 
https://github.com/bitsongofficial/go-bitsong/blob/84691c819214a1f9b9dd844ea2b49b7ccc8ece1b/proto/bitsong/nft/v1beta1/nft.proto#L63-L71

Here, the `seq` attribute should correspond to the sequence value for an NFT instance.
It would mean that in the case of a "normal" NFT (not a print,  a.k.a. `Edition`), this value is equal to 0. 
And it should be the same also for a `MasterEdition` NFT which will be used to generate the `prints` (or `Editions`).

For the `prints`, this value is incremented at each `print`.

Am I right about that?
If so, it could be useful to edit the comment at line 68 to make it more explanatory.

**Comment by go-btsg** [comment]
What comment do you suggest? (`normal nft` was meaning that not printed nft)

**Comment by Giorgionocera** [comment]
Maybe something like:
"MasterEdition / Normal (corresponding to unique version) nft".
What do you think?

**Comment by go-btsg** [comment]
Okay, such comment could be added.
