### ISSUE TITLE
Query collection by Authority

### ISSUE THREAD

**Issue by giorgionocera** [bitsongofficial/go-bitsong#162]
In the `nft` module it could be useful to query the collections by authority. This would add the `Collections` query.
Moreover, it could be useful to paginate the results (since they can become a large number).

An example of improving the collection query can be taken by the `fantoken` module. 

Here is the `FanTokens` query definition.
https://github.com/bitsongofficial/go-bitsong/blob/84691c819214a1f9b9dd844ea2b49b7ccc8ece1b/proto/bitsong/fantoken/v1beta1/query.proto#L22-L24

https://github.com/bitsongofficial/go-bitsong/blob/84691c819214a1f9b9dd844ea2b49b7ccc8ece1b/proto/bitsong/fantoken/v1beta1/query.proto#L39-L49

It could also be useful to provide results in cases like:
https://marketplace/authority_address

What do you think about that?

**Comment by Giorgionocera** [comment]
> when collection owner is empty, could return full collections.

I prefer this approach 💪
