### ISSUE TITLE
Provide non-transferable feature

### ISSUE THREAD

**Issue by giorgionocera** [bitsongofficial/go-bitsong#164]
In some usage of the `nft` technology, it could be very useful to provide non-transferable nft.
This kind of token, once they are minted, cannot be transferred to another owner.
To implement such a function, maybe it could be enough to add the attribute `transferable` to the nft `metadata` such that if it is false, the nft owner (both it is a `master edition` (or normal nft) and a `print`) cannot be changed after minting.
Obviously, this attribute should later be checked in the TransferNFT method, to verify if the operation is legit or not.

What do you think about that?

**Comment by go-btsg** [comment]
I think few people will need to transfer permission - e.g. NFT collection owner - they will need to transfer this to users.

**Comment by go-btsg** [comment]
Collection owner will need to determine if newly minted nfts are transferrable or not. Or transfer feature disable per collection? So that collection owner can restrict nft transfer?

**Comment by angelorc** [comment]
There are some use cases, for example Ticket as NFT where its necessary to lock the NFT, I think we can add a new flag `--transferable`, so any user can choose the best case

**Comment by Giorgionocera** [comment]
> I think few people will need to transfer permission - e.g. NFT collection owner - they will need to transfer this to users.

Yeah, it could be true. In such a case, I think that the `transferable` attribute could, for example, also be changed after the first transfer.

**Comment by angelorc** [comment]
> > I think few people will need to transfer permission - e.g. NFT collection owner - they will need to transfer this to users.
> 
> Yeah, it could be true. In such a case, I think that the `transferable` attribute could, for example, also be changed after the first transfer.

We don't need to add the flag transfer after the first transfer, it could be transfered with the `mint` op

**Comment by Giorgionocera** [comment]
> We don't need to add the flag transfer after the first transfer, it could be transfered with the `mint` op

Yeah, it is correct for the `print`s.
But what about a "normal" nft? (Unique one, without edition). 

If I'm not wrong, ATM the `createNFT` creates the NFT directly to the sender (owner). Maybe we can modify it to make it possible to create an NFT and mint it directly to another address.

**Comment by angelorc** [comment]
Yes the `createNFT` send directly without any check on `transferability` so again we don't need to make it transferable and the untrasferable.

**Comment by Giorgionocera** [comment]
Referenced on issue #176.
