### ISSUE TITLE
Query NFTs by Authority

### ISSUE THREAD

**Issue by giorgionocera** [bitsongofficial/go-bitsong#165]
In the `nft` module it could be useful to query the `nft`s by authority, similarly to how it could be done with the `collections`.
Moreover, it could be useful to paginate the results (since they can become a large number).

Do you agree?

**Comment by go-btsg** [comment]
Yea, I agree on adding paginations for queries. I think we already have querying nfts by owner.
`bitsongd query nft nfts-by-owner [owner]`

**Comment by Giorgionocera** [comment]
Nice!
With respect to the `owner` and `authority` they are different attributes.
So we could think to add the authority (which is who has the ability to modify the `metadata`) query.
What do you think about it?

**Comment by angelorc** [comment]
The pagination is already integrated in the grpc query, howver I think we should set a new index on the store

**Comment by angelorc** [comment]
This feature could be handled by an offchain indexer (for example subquery network).
