### ISSUE TITLE
Usage of UpdateAuthority for Collections

### ISSUE THREAD

**Issue by giorgionocera** [bitsongofficial/go-bitsong#166]
In the `nft` module, the `Collection` object is equipped also with the `UpdateAuthority` attribute.
ATM the `UpdateAuthority` field is only used in the `CreateNFT` method to verify if the nft creator, is the `UpdateAuthority` for the `collection` he wants to create the token to

https://github.com/bitsongofficial/go-bitsong/blob/84691c819214a1f9b9dd844ea2b49b7ccc8ece1b/x/nft/keeper/nft.go#L129-L131

It seems to be missing a method to update a `Collection` (i.e., for example, `symbol`, or `name`, or `uri`).

https://github.com/bitsongofficial/go-bitsong/blob/84691c819214a1f9b9dd844ea2b49b7ccc8ece1b/proto/bitsong/nft/v1beta1/tx.proto#L22-L23

While for `metadata` a method is available

https://github.com/bitsongofficial/go-bitsong/blob/84691c819214a1f9b9dd844ea2b49b7ccc8ece1b/proto/bitsong/nft/v1beta1/tx.proto#L18-L20

Is this an intentional lack? If so, why?

**Comment by go-btsg** [comment]
I think there should be fields that can be edited confirmed.

**Comment by angelorc** [comment]
We should discuss more about it. I think we should remove the possibility to edit collections.
