### ISSUE TITLE
EventMetadataAuthorityUpdate and EventMintAuthorityUpdate arguments

### ISSUE THREAD

**Issue by giorgionocera** [bitsongofficial/go-bitsong#167]
In the `nft` module, inside the `nft/keeper/metadata.go` file, when `UpdateMetadataAuthority` method is called (if it works as expected) an event of type `EventMetadataAuthorityUpdate` is emitted.
This method expects two parameters 
https://github.com/bitsongofficial/go-bitsong/blob/84691c819214a1f9b9dd844ea2b49b7ccc8ece1b/proto/bitsong/nft/v1beta1/nft.proto#L115-L118

Which should be the id of the updated `Metadata` and the new `Authority`.

It seems that the first argument is wrong. It is passed the sender address and not the `Metadata` id.

https://github.com/bitsongofficial/go-bitsong/blob/84691c819214a1f9b9dd844ea2b49b7ccc8ece1b/x/nft/keeper/metadata.go#L106-L109

Similarly, it happens for the `UpdateMintAuthority` method

https://github.com/bitsongofficial/go-bitsong/blob/84691c819214a1f9b9dd844ea2b49b7ccc8ece1b/x/nft/keeper/metadata.go#L125-L128

Is it an error?

**Comment by go-btsg** [comment]
It's an error, good catch.
