### ISSUE TITLE
Use "key" in keyName

### ISSUE THREAD

**Issue by giorgionocera** [bitsongofficial/go-bitsong#170]
In the `nft` module, the `key` functions used to generate the keys to save/retrieve elements from the store

https://github.com/bitsongofficial/go-bitsong/blob/84691c819214a1f9b9dd844ea2b49b7ccc8ece1b/x/nft/types/keys.go#L28-L34

could be renamed to `Key`+`AttributeName`. 

This is not a big issue.  It only helps to increase the readability of the code, as it is done in the `fantoken` module.

https://github.com/bitsongofficial/go-bitsong/blob/84691c819214a1f9b9dd844ea2b49b7ccc8ece1b/x/fantoken/types/keys.go#L26-L34

For sure, it is a low-priority improvement.
Do you agree?

**Comment by angelorc** [comment]
This is related to the issue #171
