### ISSUE TITLE
TestCollectionNftsCreationAndQuery test is not complete

### ISSUE THREAD

**Issue by giorgionocera** [bitsongofficial/go-bitsong#172]
In the `nft` module, inside the `nft/keeper/collection_test.go` file, a set of tests are proposed.
One of them, the `TestCollectionNftsCreationAndQuery` seems to need to be implemented with further verification
https://github.com/bitsongofficial/go-bitsong/blob/84691c819214a1f9b9dd844ea2b49b7ccc8ece1b/x/nft/keeper/collection_test.go#L77-L85

**Comment by go-btsg** [comment]
Ok
