### ISSUE TITLE
Renaming GetCollectionNfts

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/go-bitsong#174]
In the `nft` module, since the method `GetCollectionNfts` returns a list of NFTs by collection
https://github.com/bitsongofficial/go-bitsong/blob/84691c819214a1f9b9dd844ea2b49b7ccc8ece1b/x/nft/keeper/nft.go#L29

to maintain the same naming convention with the other created methods, I suggest to rename the method to `GetNFTsByCollectionId` or `GetNFTsByCollection`, since a `collectionID` is provided as the parameter and NFTs are returned.
This is not a big issue, low-priority for sure, but I think it should be done.

**Comment by go-btsg** [comment]
Okay

**Comment by go-btsg** [comment]
Covered on this commit
https://github.com/bitsongofficial/go-bitsong/pull/153/commits/e830e73dbbf448ecbb7837c3647c007bce9819e9

**Comment by Giorgionocera** [comment]
Thank you!
