### ISSUE TITLE
Burning NFTs

### ISSUE THREAD

**Issue by giorgionocera** [bitsongofficial/go-bitsong#176]
In the `nft` module, I did not see any burn method for the NFTs. 
Do we want to include such a feature?

**Comment by go-btsg** [comment]
I would like to have @angelorc for this.

**Comment by Giorgionocera** [comment]
I will post here the result of the discussion with @angelorc:

Only **non-transferable** NFTs can be burned. It would be created as a "black hole" account which at the moment will contain all the burned NFT.
So, the burning action will transfer the non-transferable NFT to a "black hole account".
