### ISSUE TITLE
MetadataID 0 not used

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/go-bitsong#178]
In the `nft` module, the `CreateNFT` method in the `nft/keeper/nft.go` file, is responsible for the creation of a new NFT. inside this method, after retrieving the `collection` (to which the NFT belongs) and verifying that it is owned by the NFT creator, the new `metadata` is stored.

This process happens through lines 134-150 
https://github.com/bitsongofficial/go-bitsong/blob/84691c819214a1f9b9dd844ea2b49b7ccc8ece1b/x/nft/keeper/nft.go#L122-L175

Line 134 generates the new `metadataId` for that specific collection. Although, as I discussed in #159 , I would like to use a global id for the metadata (and not metadata depending on the collection), here the question is a more general one:

Is the fact that you cannot use id 0 for metadata an intentional thing?

**Comment by Giorgionocera** [comment]
The same also happens for the `collectionId` in the `CreateCollection` method (inside the file `nft/keeper/msg_server.go`)
https://github.com/bitsongofficial/go-bitsong/blob/84691c819214a1f9b9dd844ea2b49b7ccc8ece1b/x/nft/keeper/msg_server.go#L145-L168

We agree on the fact that this helps in verifying if at least a collection is created (0 values, indicate no collection is present). But is this the wanted behavior? 
Or do we prefer to use an error value return together with the ID to highlight the kind of result?

**Comment by go-btsg** [comment]
`Is the fact that you cannot use id 0 for metadata an intentional thing?`
Most of nft ids start from 1 - 0 is just for development and users like to read from 1.

**Comment by Giorgionocera** [comment]
It is okay for me. If it is okay also for @angelorc we can close this.

**Comment by go-btsg** [comment]
Okay

**Comment by Giorgionocera** [comment]
@angelorc confirmed it is ok.
