### ISSUE TITLE
Normal NFT

### ISSUE THREAD

**Issue by giorgionocera** [bitsongofficial/go-bitsong#179]
In the `nft` module, which is the difference between a _normal_ NFT (MasterEdition equal to nil) and an NFT with MasterEdition and `MaxSupply` = 1?
I think the two represent exactly the same object since both of them have an NFT and no one can create other prints.
So, why there is the possibility to generate two different versions for the same kind of object?
This could generate inconsistencies.
What do you think about it?

**Comment by go-btsg** [comment]
It's because of struct we have, do you like to make it to be consistent to have MaxSupply=1 for _normal_ NFT?

**Comment by Giorgionocera** [comment]
IMHO, it is a way to make it more consistent. But I ask you and @angelorc if you agree with me.

**Comment by Giorgionocera** [comment]
@angelorc agrees on making them more consistent.

**Comment by Giorgionocera** [comment]
In this way, we can use only the `maxSupply` as an argument in input for the messages, instead of passing the whole `masterEdition`.
