### ISSUE TITLE
First NFT owner

### ISSUE THREAD

**Issue by giorgionocera** [bitsongofficial/go-bitsong#181]
In the `nft` module, the method `CreateNFT`, automatically creates the first NFT assigning it to the sender of the message. In this way, it is not possible to create an NFT directly for someone else, but you first need to create an NFT and then, you need to `transfer` the NFT to another `owner`.
Why did we do this choice?

**Comment by go-btsg** [comment]
Okay, new owner could be provided as part of create nft.

**Comment by angelorc** [comment]
We should go into deep and analyze some other use cases
