### ISSUE TITLE
Discussion on NFT management fees

### ISSUE THREAD

**Issue by giorgionocera** [bitsongofficial/go-bitsong#183]
In the `nft` module, ATM the unique fee available is the `issue` one which is used both in `CreateNFT` and in the `PrintEdition` methods. 
This means that both the actions of creating a new NFT (_master edition_ or _normal NFT_) and the minting (print of an edition) are connected to this fee.
IMHO, the `mint` fee should be different from the `issue` one and they should be two parameters of the module on the chain.
What do you think?

We can also give look around to see how other "guys" 😏 are used to working.

| **Service**  | **Create Collection**     | **Issue NFT** | **Print Edition**                           | **Mint through Marketplace** |
| ------------ | ------------------------ | -------------- | ------------------------------- | ------------------------------ |
| BitSong (now)  | 0BTSG                         | 1BTSG              | 1BTSG                                          |                                                     |
| Stargaze      | 1000STARS (with NFTs) | -                        | 0 for the SmartContract Owner | at the creator's discretion (min 50STARS)|

**Comment by go-btsg** [comment]
Okay - new params could be added for print fee.
