### ISSUE TITLE
TransferNFT newOwner validation

### ISSUE THREAD

**Issue by giorgionocera** [bitsongofficial/go-bitsong#185]
In the `nft` module, inside the `nft/keeper/nft.go` file, as for #184, verification is not directly performed on the `owner` address. Even if I know that the `SetNFT` method (which is called at line 247) generates a panic error if the `owner` is empty, maybe, it could be kinder to add a check before and avoid the panic generation on the `SetNFT` method (which should only be the fallback).
https://github.com/bitsongofficial/go-bitsong/blob/84691c819214a1f9b9dd844ea2b49b7ccc8ece1b/x/nft/keeper/nft.go#L236-L255

In the end, also here I don't like to split events between msg_server and the keeper, and, for this reason, I would like to emit events directly on the methods belonging to msg_server (as it is done for the SignMetadata method for example).

What do you think?

**Comment by go-btsg** [comment]
I think it's okay to emit event on msg server.

**Comment by Giorgionocera** [comment]
Okay, nice 💪 

And what about verifying if the `owner` address is a valid address?

**Comment by go-btsg** [comment]
Owner address is verified on ValidateBasic fyi. Usually avoiding duplicated execution would be good.

**Comment by go-btsg** [comment]
1. ValidateBasic is executed on chain side as well not only client side
2. Okay - will make verifications for Owner part.

**Comment by Giorgionocera** [comment]
1. Do you mean [this]( https://docs.cosmos.network/main/building-modules/msg-services.html#validation )?
If so, we should implement this. It would be nice!
