### ISSUE TITLE
Uniform implementations

### ISSUE THREAD

**Issue by giorgionocera** [bitsongofficial/go-bitsong#186]
In the `nft` module, it happens that sometimes we have (as is normal) part of a similar code.
For example, it happens for the `GetAllCollections` method
https://github.com/bitsongofficial/go-bitsong/blob/84691c819214a1f9b9dd844ea2b49b7ccc8ece1b/x/nft/keeper/collection.go#L42-L55
and the `GetAllLastMetadataIds` method
https://github.com/bitsongofficial/go-bitsong/blob/84691c819214a1f9b9dd844ea2b49b7ccc8ece1b/x/nft/keeper/metadata.go#L9-L22

Even if they share a big part of the code they present some differences in the implementation.
This is a very low-priority issue, but it could be useful to uniform the implementations.

**Comment by go-btsg** [comment]
Okay

**Comment by Giorgionocera** [comment]
Similarly, we could refactor a bit for `GetLastMetadataId` method.

**Comment by Giorgionocera** [comment]
The same could be done between `GetAllMetadata` WRT `GetAllCollections`.
