### ISSUE TITLE
UpdateMetadataAuthority and UpdateMintAuthority

### ISSUE THREAD

**Issue by giorgionocera** [bitsongofficial/go-bitsong#188]
In the `nft` module, inside the `nft/keeper/metadata.go` file, there is a method, called `UpdateMetadataAuthority`, that is used to update the authority metadata.

https://github.com/bitsongofficial/go-bitsong/blob/84691c819214a1f9b9dd844ea2b49b7ccc8ece1b/x/nft/keeper/metadata.go#L94-L111

In such a scenario, even considering the `ValidateBasic` method

https://github.com/bitsongofficial/go-bitsong/blob/84691c819214a1f9b9dd844ea2b49b7ccc8ece1b/x/nft/types/msgs.go#L291-L298

The `NewAuthority` address is not validated, and ATM, it can also be an empty string.

Also here, I don't like to split events between msg_server and the keeper, and, for this reason, I would like to emit events directly on the methods belonging to msg_server (as it is done for the SignMetadata method for example).

The same is also valid for the `UpdateMintAuthority` method.

**Comment by Giorgionocera** [comment]
Similarly, in the `UpdateCollectionAuthority` method we should validate the NewAuthority address which ATM can also be an empty string.

This issue was included in #192 . Moved here to improve priority management.
