### ISSUE TITLE
Events on MsgServer

### ISSUE THREAD

**Issue by giorgionocera** [bitsongofficial/go-bitsong#189]
In the `nft` module, inside the `nft/keeper/msg_server.go` the `CreateNFT` method invokes the `CreateNFT` implementation of the keeper.  Here it could be better to move the event emission on the `msg_server.go` file to make it uniform with other methods.
This issue is related to #180.

**Comment by Giorgionocera** [comment]
Similarly, it happens for the `TransferNFT` method #185.

**Comment by Giorgionocera** [comment]
Similarly, it happens for the `PrintEdition` method #184.

**Comment by Giorgionocera** [comment]
Similarly, it happens for the `UpdateMetadataAuthority` and `UpdateMintAuthority` methods #188.
