### ISSUE TITLE
UpdateMetadataAuthority and not mutable metadata

### ISSUE THREAD

**Issue by giorgionocera** [bitsongofficial/go-bitsong#200]
In the `nft` module, ATM the `UpdateMetadataAuthority` method is able to modify the `MetadataAuthority` even if the metadata is mutable no more (`isMutable` = false).
The method is also involved in issue #188.
IMHO, once the `metadata` is mutable no more (the `isMutable` attribute is set to `false`), neither the `MetadataAuthority`should be able to change.
What do you think?

**Comment by Giorgionocera** [comment]
After a meeting with @angelorc , he agrees with this vision. Moreover, he also agrees with the fact of using the `MetadataAuthorithy` value to verify if it is mutable or not (empty address corresponds to `isMutable = false`).
