### ISSUE TITLE
NFT errors adjust

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/go-bitsong#206]
In the `nft` module, on the `nft/types/errors.go`, I would modify the text of some errors:
- [x] `ErrNFTDoesNotExist` from "nft does not exist" to "**NFT** does not exist"
- [x] `ErrNotNFTOwner` from "not the owner of nft" to "not the owner of the **NFT**"
- [x] `ErrNotMasterEditionNft` from "not master edition nft" to "not master edition **NFT**"
- [x] 	`ErrInvalidNftId` from "invalid nft id" to "invalid **NFT** id"
- [x] `ErrMasterEditionNftDoesNotExists` from "master edition nft does not exists" to "master edition **NFT** does not **exist**"
What do you think?

**Comment by go-btsg** [comment]
Changes are added on this commit
https://github.com/bitsongofficial/go-bitsong/pull/153/commits/b56b7e91b96fc34d786d96f65965071c7fcbd9ec

**Comment by Giorgionocera** [comment]
Thank you!
