### ISSUE TITLE
events.go file in nft module

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/go-bitsong#207]
In the `nft` module, there is a file, the `nft/types/events.go`, which is empty.
Since `TypedEvents` are used, this file no longer needs to exist.

**Comment by go-btsg** [comment]
Removed on this commit
https://github.com/bitsongofficial/go-bitsong/pull/153/commits/d4ccc54326a048a5886d4396b5b6f1356c05b5a8

**Comment by Giorgionocera** [comment]
Thank you.
