### ISSUE TITLE
genesis_test.go file in nft module

### ISSUE THREAD

**Issue by giorgionocera** [bitsongofficial/go-bitsong#209]
In the `nft` module, there is the `nft/types/genesis_test.go` file, which should contain the tests for the genesis validation, including those for genesis file parsing.
These tests are missing ATM and we should implement them.

**Comment by go-btsg** [comment]
Here's the commit for genesis tests
https://github.com/bitsongofficial/go-bitsong/pull/153/commits/b3d719ad03c305c9289e775f45c033cdb6dabcec

Just have put genesis init and export functionalities on keeper, to follow latest Cosmos coding standard.

**Comment by Giorgionocera** [comment]
On that commit, it is also done what is asked in #156. Thank you!
The only thing I ask you is to improve the tests by also adding some other test examples, please.
