### ISSUE TITLE
NFT types suggestions

### ISSUE THREAD

**Issue by giorgionocera** [bitsongofficial/go-bitsong#210]
In the `nft` module, there is the `nft/types/nft.go` file, which contains utilities for the `nft` type.

I have some questions/suggestions for these:
1. As for point 5 in #159, why do we use `CollectionID`, `MetadataID`, and `SequenceNumber` for each NFT as the id? Is there a motivation?
2. The two functions `IsValidNftId` and `NftIdToBytes` could be merged in a single function with error if the `nftID` is not valid, since they share a very important part of logic.

https://github.com/bitsongofficial/go-bitsong/blob/84691c819214a1f9b9dd844ea2b49b7ccc8ece1b/x/nft/types/nft.go#L19-L52

**Comment by go-btsg** [comment]
For 1st one, this was what @angelorc  suggested.
For 2nd one, I will make changes to use same codebase.

**Comment by go-btsg** [comment]
For 2nd one, it's done on this commit.
https://github.com/bitsongofficial/go-bitsong/commit/6afb22c08474840168f31eed12907efc1d92bc3a

**Comment by Giorgionocera** [comment]
Yeah, for me, 2nd point is ok after commit [6afb22c](https://github.com/bitsongofficial/go-bitsong/commit/6afb22c08474840168f31eed12907efc1d92bc3a).
