### ISSUE TITLE
Messages for collection verifying nft module

### ISSUE THREAD

**Issue by giorgionocera** [bitsongofficial/go-bitsong#213]
In the `nft` module, there is the `nft/types/msgs.go` file, which contains the messages.
Here there exist two messages which are unused and should be removed:
```
TypeMsgVerifyCollection            = "verify_collection"
TypeMsgUnverifyCollection        = "unverify_collection"
```
Do you agree?

**Comment by go-btsg** [comment]
Resolved on this commit
https://github.com/bitsongofficial/go-bitsong/commit/3febed504e6e55be7ff3f16a2350da25f559b319

Please close the issue if things are okay @Giorgionocera

**Comment by Giorgionocera** [comment]
This is also used in CLI flags. I think we should also remove it from there.

https://github.com/bitsongofficial/go-bitsong/blob/3febed504e6e55be7ff3f16a2350da25f559b319/x/nft/client/cli/flags.go#L107-L114

Do you agree?

**Comment by lukfm-mms** [comment]
i'm agree
