### ISSUE TITLE
Signing window is too small for slashing

### ISSUE THREAD

**Issue by kwunyeung** [bitsongofficial/go-bitsong#45]
The slashing condition for uptime is 0.5 x 100 blocks which is less than 10mins to be jailed at start, 5mins after the first 100 blocks.

https://github.com/bitsongofficial/go-bitsong/blob/bd6d3eca2a4ec453e07fd1ff5370d4e34022dd2b/testnet-1/genesis.json#L499

**Comment by angelorc** [comment]
thanks, we are going to change it with these params:

```
      "params": {
        "max_evidence_age": "120000000000",
        "signed_blocks_window": "10000",
        "min_signed_per_window": "0.050000000000000000",
        "downtime_jail_duration": "60000000000",
        "slash_fraction_double_sign": "0.050000000000000000",
        "slash_fraction_downtime": "0.000100000000000000"
      },
```

**Comment by angelorc** [comment]
New genesis is online, but better to wait the tag v0.1.0
