### ISSUE TITLE
BitSong Track Metadata

### ISSUE THREAD

**Issue by bitsongofficial** [bitsongofficial/go-bitsong#52]
## This is the last BitSong Track Metadata implementation

To all Music Providers, we need feedbacks for this issue
If you consider that the structure has to be changed or improved, feel free to comment on the issue

```json
{
  "title": "The show must go on",
  "artists": ["Artist 1", "Artist 2", "Artist 3"],
  "feat": ["Singer 1"],
  "producers": ["Producer 1"],
  "images": [
    { "32x32": "ipfs://Qm........"},
    { "500x500": "ipfs://Qm........"}
  ],
  "sources": [
    { "preview": "ipfs://Qm...." },
    { "hls": "ipfs://Qm...." },
    { "opus": "ipfs://Qm...." },
    { "mp3_low": "ipfs://Qm...." },
    { "mp3_high": "ipfs://Qm...." }
  ],
  "duration": 15001,
  "number": 1,
  "tags": ["tag 1", "tag 2", "tag 3"],
  "genre": "Pop",
  "mood": "Energetic",
  "label": "My best label",
  "credits": "Creative Commons",
  "external_ids": [
    { "youtube": "M7Iwkxy_Hjw" },
    { "spotify": "12487825" }
  ],
  "external_urls": [
    { "youtube": "https://www.youtube.com/watch?v=y6veLh2b1Js" },
    { "soudcloud": "https://soundcloud.com/bangtan/thankyouarmy2020" }
  ]
}
```

**Comment by tee100x** [comment]
looks solid, good/useful info. thorough, however could possibly use/integrate songwriter credits. they can be hard to gather/aggregate but making it a focus/category from the start helps with that process. maybe that's what "credits" are..?
also, potentially a "rightsholder" or "song owner" type field that says who owns the song, once tokenized this field could become competitive and sought after
