### ISSUE TITLE
Minting fan token amount

### ISSUE THREAD

**Issue by angelorc** [bitsongofficial/go-bitsong#56]
I tried to mint some fantoken, when we `mint` a new `fantoken` it will add 6 standard decimal and the result could be out of the proposed intentions.

## Command
```
bitsongd tx fantoken mint clay --recipient bitsong1lemmdcgn087pd380p54q0f45pe7vrylcetu529 --amount 1000 --from validator --chain-id test
```

## What I expect
I expect that with this command I will mint `1000 clay`. Currently the chain mint `1000000000uclay`

I think the best approach is to change the command to accept something like that

```
..... fantoken mint uclay --amount 1000000000
```

with that expression the account is sure to get the specified amount.

https://github.com/bitsongofficial/go-bitsong/blob/module/fantoken/x/fantoken/keeper/keeper.go#L166

**Comment by chaindbkey** [comment]
fixed in https://github.com/bitsongofficial/go-bitsong/tree/module/fantoken
