### ISSUE TITLE
Change issue fee in fan token module

### ISSUE THREAD

**Issue by angelorc** [bitsongofficial/go-bitsong#59]
The `issue-fee` should be an `sdk.Coin` string, example: `--issue-fee 1ubtsg` and not `--issue-fee 1`

Command:
`bitsongd tx fantoken issue --name Angelo --symbol angelo --max-supply 1000 --issue-fee 1000000 --from validator --chain-id test -b block`

**Comment by chaindbkey** [comment]
what happens if the user input `--issue-fee 1uxxx`, not ubtsg - bondDenom?
Does it exactly need to put the bond denom in the cli?

**Comment by angelorc** [comment]
yes we could use `sdk.ParseCoin` and the flag will be `--issue-fee 12ubtsg (bond denom)` the fee then should be distribuited with the fee pool
