### ISSUE TITLE
Mint/Burn fantoken, change denom to symbol

### ISSUE THREAD

**Issue by angelorc** [bitsongofficial/go-bitsong#60]
When you issue a new fantoken, you need to specify the `symbol`. In my example I issued the symbol `angelo` it mean that in the state it's stored as `uangelo`.

`bitsongd tx fantoken issue --name Angelo --symbol angelo --max-supply 1000 --issue-fee 1000000`

If you want to mint a new fantoken, you must specify the `symbol`, the current command is accepting the `denom` and it should be changed with `symbol`

From:
`bitsongd tx fantoken mint uangelo --recipient $(bitsongd keys show validator -a) --amount 1`

To:
`bitsongd tx fantoken mint angelo --recipient $(bitsongd keys show validator -a) --amount 1`

----

From:
`bitsongd tx fantoken burn uangelo --amount 1`

To:
`bitsongd tx fantoken burn angelo --amount 1`

**Comment by chaindbkey** [comment]
This is conflict with https://github.com/bitsongofficial/go-bitsong/issues/56
We discussed to use denom, not symbol here.

**Comment by angelorc** [comment]
Better to write somewhere (for example to btsg.dev) the difference between denom and symbol
