### ISSUE TITLE
Issuing a token w/ the same name twice

### ISSUE THREAD

**Issue by Pharaon1993** [bitsongofficial/go-bitsong#81]
In the bigbang-test-2 chain:

If I issue a token w/ an already taken name, it gives me an "Denom Already Exists" error. I created this token:

(Tx Hash: F1EADFF4B01E1A563EF7C58CCE669C0869C95926A44E9DC242D9990A868BC938)

`bitsongd tx fantoken issue --issue-fee=1000000ubtsg --max-supply=1000000 --symbol="bug" --description="" --from=hathor --chain-id=bigbang-test-2 --fees=200ubtsg --name="BugToken"`

If I check, I can tell I own this token now:

`bitsongd query fantoken owner bitsong1uh0ncteup7tles2t6v32cc4adrfjhjzk2jnxpu`

- max_supply: "1000000"
  meta_data:
    base: ft518F03EDBB4A1E66A694B6833A2235067692E8C0
    denom_units:
    - denom: ft518F03EDBB4A1E66A694B6833A2235067692E8C0
    - denom: bug
      exponent: 6
    display: bug
  mintable: true
  name: BugToken
  owner: bitsong1uh0ncteup7tles2t6v32cc4adrfjhjzk2jnxpu

If I try to recreate that same token:

`bitsongd tx fantoken issue --issue-fee=1000000ubtsg --max-supply=1000000 --symbol="bug" --description="" --from=hathor --chain-id=bigbang-test-2 --fees=200ubtsg --name="BugToken"`

`bitsongd query tx --type=hash 0C63C51BB7FE63B6E1BEFC19BD7B52860C57A07E83ADAD799A0FFB6C926B89F1`

I get the error: failed to execute message; message index: 0: denom already exists: ft518F03EDBB4A1E66A694B6833A2235067692E8C0

That denom matches my BugToken that I just made. If I rename my token to BuToken,

`bitsongd tx fantoken issue --issue-fee=1000000ubtsg --max-supply=1000000 --symbol="bug" --description="" --from=hathor --chain-id=bigbang-test-2 --fees=200ubtsg --name="BuToken"`

It works w/ a tx hash of BBEF623C4E6A0217C09B77EA4DCF4C16C1651FD301393F152036F5594417E447

I can check  my ownership of both tokens:

`bitsongd query fantoken owner bitsong1uh0ncteup7tles2t6v32cc4adrfjhjzk2jnxpu`

If I transfer the token to someone else, I still can't make a token w/ a new name.

I can go into the testnet guide and make an Angelo's token even though other people have made that same token. But I can't reuse the same name twice myself.

**Comment by angelorc** [comment]
Sorry, I missed this issue.

Thank you for your time.
This is a protection, if for some reason (eg network busy) you send 2 txs with the same denom, it will return an error.

Another account could eventually use the same symbol, but the fantoken hash (the denom ft<hash>) will be different
