### ISSUE TITLE
Bug Sinfonia Testnet

### ISSUE THREAD

**Issue by richiebinance** [bitsongofficial/go-bitsong#97]
I have done swap 2 transaction .. but next swap transaction still error .. i have 2200 BTSG but cannot swap .
![Screenshot_2022-05-09-23-17-29-902_com kiwibrowser browser](https://user-images.githubusercontent.com/82761397/167454499-6685d777-3d1b-4e91-80df-965bb531970e.jpg)

**Comment by Giorgionocera** [comment]
This is not the right repository to add issues for Sinfonia. 
Please give a look at the correct repo, there are different issues with the same "problem". 
So please, avoid duplicated issues.
