### ISSUE TITLE
Bug Report Sinfonia Testnet

### ISSUE THREAD

**Issue by malingbandi** [bitsongofficial/go-bitsong#98]
i can't do swap on sp 1% & 3% but sp 5% works. please fix.
my address : bitsong13yez56pph5qnajftfhfnrquqcyl87zxepsuk5w
![Screenshot (59)](https://user-images.githubusercontent.com/74755788/167457405-20563792-5f62-4adc-ad7e-eb9ecde8bbb3.png)

**Comment by ctrl-Felix** [comment]
Please try to increase slippage even more than or just wait a bit for the liquidity to settle. The problem was too much trades with not a lot of liquidity which ended up in a very dynamic market situation
